### ISSUE TITLE
Bug: hover on inactive links in header

### ISSUE THREAD

**Issue by MarPostovik** [p-foundation/pink-app#31]
**Description**
In our project, we have the header, which has links to different pages of the website. But one link does not link anywhere. It is the link that tells us the name of the page, where we already are. But when we hover over it or click and hold our mouse we still see that it changes color as if it should link somewhere else. I suggest removing the styles for active and hover state for that link.

**To Reproduce**
1. Go to 'index.html'
2. Hover over the 'Главная' link or click and hold your mouse.
3. You'll see that the link changes color to pink when hovered and to grey when clicked.

**Expected behavior**
The link shouldn't react. There should not be any change at _hover_ or _down_  state because this link just shows on which page we are and does not link anywhere.

**Video**

https://github.com/p-foundation/pink-app/assets/126704357/0c00e6ea-b71a-46dc-ba6f-ec65dbc3410a

**Desktop:**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [122.0.6261.113]
 
**Additional context**

Here is how the code for hover and active state looks like now: 
```css
.header__navigation-link:hover{
    color: rgb(178, 40, 102);
}

.header__navigation-link:active{
    color: rgb(255, 255, 255, 0.5);
}
``` 

**Quick Instruction for Working on the Issue**
‼️ Before checking out to a new branch, ensure you have the latest updates from the main by running `git pull` command.
- **Please create a new branch**, and name it `fix-hover-on-inactive-link`
- **Make Changes:** in the file `header__navigation-link.css`  instead of the code that I've provided in additional context, write these lines:
```css
.header__navigation-link:not(.header__navigation-link_active):hover{
    color: rgb(178, 40, 102);
}

.header__navigation-link:not(.header__navigation-link_active):active{
    color: rgb(255, 255, 255, 0.5);
}
``` 
- **Test thoughtfully:** In the live server check a few times that in the `index.html` the link that tells us "Главная" doesn't react on hover and active state.
- **Open a pull request:** reference the specific issue in your PR description using the following format:
`This pull request resolves [#issue_number](link_to_the_issue)`. Replace `issue_number` with the actual issue number and `link_to_the_issue` with the link to the respective issue. For example:

```bash
This pull request resolves [#123](https://github.com/username/repository/issues/123)
```
